# Prometheus configuration for HedgeLock v2.0
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hedgelock-monitor'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Position Manager metrics
  - job_name: 'position-manager'
    static_configs:
      - targets: ['position-manager:8009']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Loan Manager metrics
  - job_name: 'loan-manager'
    static_configs:
      - targets: ['loan-manager:8010']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Reserve Manager metrics
  - job_name: 'reserve-manager'
    static_configs:
      - targets: ['reserve-manager:8011']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Safety Manager metrics
  - job_name: 'safety-manager'
    static_configs:
      - targets: ['safety-manager:8012']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Trade Executor metrics
  - job_name: 'trade-executor'
    static_configs:
      - targets: ['trade-executor:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Risk Engine metrics
  - job_name: 'risk-engine'
    static_configs:
      - targets: ['risk-engine:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Funding Engine metrics
  - job_name: 'funding-engine'
    static_configs:
      - targets: ['funding-engine:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Collector metrics
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Kafka exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']