version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: host
    environment:
      - DATABASE_URL=postgresql://hedgelock:hedgelock@localhost:5432/hedgelock
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hedgelock
      POSTGRES_PASSWORD: hedgelock
      POSTGRES_DB: hedgelock
    network_mode: host

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: host

volumes:
  postgres-data:
  redis-data: