name: Position Manager Tests

on:
  push:
    paths:
      - 'src/hedgelock/position_manager/**'
      - 'tests/unit/position_manager/**'
      - '.github/workflows/position-manager-tests.yml'
  pull_request:
    paths:
      - 'src/hedgelock/position_manager/**'
      - 'tests/unit/position_manager/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Run tests with coverage
      run: |
        poetry run pytest tests/unit/position_manager/ -v \
          --cov=src/hedgelock/position_manager \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-fail-under=100
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: position-manager
        name: position-manager-coverage
        fail_ci_if_error: true